[package]
name = "json-to-sitemap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sitemap = "0.4.1"
serde = { version = "1.0.110", features = ["derive"] }
serde_json = "1.0.53"
chrono = "0.4.11"
